{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAvailableRemoteVideo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hcevideocall\/hcecall\/sdkerror\/notavailableremotevideo"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/SDKError\/notAvailableRemoteVideo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Failed to access remote video because remote video is not connected"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAvailableRemoteVideo"}],"title":"HceCall.SDKError.notAvailableRemoteVideo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12HceVideoCall0aC0C8SDKErrorO018notAvailableRemoteB0yA2EmF","modules":[{"name":"HceVideoCall"}]},"hierarchy":{"paths":[["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/SDKError"]]},"references":{"doc://io.hce.HceVideoCall/documentation/HceVideoCall":{"role":"collection","title":"HceVideoCall","abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCall":{"role":"symbol","title":"HceCall","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceCall"}],"abstract":[{"type":"text","text":"class HceCall"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceCall"}],"url":"\/documentation\/hcevideocall\/hcecall"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCall/SDKError":{"role":"symbol","title":"HceCall.SDKError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKError"}],"abstract":[{"type":"text","text":"SDK Errors"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/SDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKError"}],"url":"\/documentation\/hcevideocall\/hcecall\/sdkerror"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCall/SDKError/notAvailableRemoteVideo":{"role":"symbol","title":"HceCall.SDKError.notAvailableRemoteVideo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAvailableRemoteVideo"}],"abstract":[{"type":"text","text":"Failed to access remote video because remote video is not connected"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall\/SDKError\/notAvailableRemoteVideo","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/hcecall\/sdkerror\/notavailableremotevideo"}}}